export const ARRAY_OF_COMMENTS = [
  "😎",
  "🤣🤣🤣",
/*   "💗💗💗",
  "🔥🔥🔥",
  "Qué buena esa 😂",
  "No paro de reír 🤣",
  "Totalmente de acuerdo 💯",
  "Esto es arte 🎨",
  "Me encantó 💕",
  "JAJAJA épico 😂",
  "Simplemente genial 😍",
  "¡Lo necesito ya! 😩",
  "Brutal 🔥",
  "¿Dónde firmo? 😅",
  "Esto sí que es contenido 🙌",
  "Muy cierto eso 👏",
  "Gracias por esto 🙏",
  "Top top top 🚀",
  "Estoy llorando de la risa 😂😂😂 Estoy llorando de la risa 😂😂😂 Estoy llorando de la risa 😂😂😂",
  "¡Más de esto por favor! 😍" */
];
