export const AGRADECER = [
  // Español
  "Gracias por esto 🙏",
  "Mil gracias, de verdad 💖",
  "Estoy muy agradecido/a 🙌",
  "No sabes cuánto lo aprecio 🤗",
  "Infinitas gracias 🌟",
  "De corazón, gracias ❤️",
  "Gracias por compartir esto 🙏",
  "Te lo agradezco mucho 🙏",
  "Un millón de gracias ✨",
  "Gracias por tu esfuerzo 💪",
  "Gracias, me has alegrado el día 😊",
  "Muy agradecido/a por esto 🙏",
  "Gracias por estar siempre ahí 🤝",
  "Te agradezco de todo corazón 💝",
  "Muchísimas gracias por todo 🌈",

  // Inglés
  "Thank you for this 🙏",
  "A thousand thanks, really 💖",
  "I'm very grateful 🙌",
  "You don't know how much I appreciate it 🤗",
  "Endless thanks 🌟",
  "From the bottom of my heart, thanks ❤️",
  "Thanks for sharing this 🙏",
  "I appreciate it so much 🙏",
  "A million thanks ✨",
  "Thank you for your effort 💪",
  "Thanks, you made my day 😊",
  "Very thankful for this 🙏",
  "Thanks for always being there 🤝",
  "I thank you with all my heart 💝",
  "Many thanks for everything 🌈",

  // Italiano
  "Grazie per questo 🙏",
  "Mille grazie, davvero 💖",
  "Sono molto grato/a 🙌",
  "Non sai quanto lo apprezzo 🤗",
  "Grazie infinite 🌟",
  "Dal profondo del cuore, grazie ❤️",
  "Grazie per aver condiviso 🙏",
  "Ti ringrazio tanto 🙏",
  "Un milione di grazie ✨",
  "Grazie per il tuo impegno 💪",
  "Grazie, mi hai reso felice la giornata 😊",
  "Molto grato/a per questo 🙏",
  "Grazie per esserci sempre 🤝",
  "Ti ringrazio con tutto il cuore 💝",
  "Tantissime grazie per tutto 🌈"
];
