export const JAJAJAJS = [
  'jajajajajaja 🤣',
  'hahahahaha 😂',
  'JAJAJAJAJAJA 😭',
  'Qué buena esa 😂',
  'No paro de reír 🤣',
  'Estoy llorando de la risa 😂😂😂',
  'JAJAJA épico 😂',
  'jajajaajjsjsjs 🤣',
  'hahhahaahha 🤪',
  'jajsjsjajsjsj',
  'LOL 😂😂',
  'xD xD xD',
  'jajajajajaksksks',
  'hahaha sksksksk',
  'jajajajaa qué risa 😂',
  'HAHAAHAHAHAH 🤣',
  'lmaooo 😭',
  'jajaJAjaJAjaJA 🤣🤣',
  'hahAHhahAHhahAH',
  'jsjsjsjsjsjsjsjsjs',
  'jajajjaja no puedo 😭',
  'ROFL 🤣',
  'jajajajaja literal me morí 😂',
  'AY NO JAJAJAJAJA 🤣'
];
