export const REACCIONES = [
  // Español
  "¡Increíble! 😮",
  "No me lo esperaba 🤯",
  "Jajaja, qué bueno 😂",
  "Wow, esto sí que mola 😍",
  "Me dejó sin palabras 😶",
  "Totalmente sorprendido 🤩",
  "Esto me hizo el día 😊",
  "Qué locura, no puedo creerlo 🤪",
  "Muy emocionante 🙌",
  "¡Genial! 👍",
  "Eso sí que es original 🤔",
  "Me encanta ❤️",
  "Qué nivel 😎",
  "Impresionante 👏",
  "Esto es otro nivel 🚀",
  "Súper divertido 😆",
  "No esperaba menos de ustedes 🙏",
  "Me atrapó desde el principio 🔥",
  "Tremendo trabajo 💪",
  "Esto es arte puro 🎨",
  
  // Inglés
  "Amazing! 😮",
  "Didn’t see that coming 🤯",
  "Haha, so good 😂",
  "Wow, this rocks 😍",
  "Left me speechless 😶",
  "Totally blown away 🤩",
  "This made my day 😊",
  "Crazy, can’t believe it 🤪",
  "So exciting 🙌",
  "Awesome! 👍",
  "That’s original 🤔",
  "I love it ❤️",
  "Next level stuff 😎",
  "Impressive 👏",
  "This is on another level 🚀",
  "Super fun 😆",
  "Expected nothing less from you 🙏",
  "Hooked me from the start 🔥",
  "Great job 💪",
  "Pure art 🎨",
  
  // Italiano
  "Incredibile! 😮",
  "Non me lo aspettavo 🤯",
  "Ahaha, che bello 😂",
  "Wow, è fantastico 😍",
  "Mi ha lasciato senza parole 😶",
  "Completamente sorpreso 🤩",
  "Mi ha migliorato la giornata 😊",
  "Che pazzia, non ci posso credere 🤪",
  "Molto emozionante 🙌",
  "Fantastico! 👍",
  "Davvero originale 🤔",
  "Mi piace ❤️",
  "Che livello 😎",
  "Impressionante 👏",
  "È un altro livello 🚀",
  "Super divertente 😆",
  "Non mi aspettavo altro da voi 🙏",
  "Mi ha catturato fin dall’inizio 🔥",
  "Ottimo lavoro 💪",
  "È pura arte 🎨"
];
