export const CRITICAS_CONSTRUCTIVAS = [
  // Español
  "Me gusta mucho, pero creo que podría mejorar en algunos aspectos.",
  "Sería genial si añadieran más opciones de personalización.",
  "La idea es excelente, solo falta pulir algunos detalles técnicos.",
  "El contenido es bueno, pero la interfaz podría ser más intuitiva.",
  "Me gustaría ver más ejemplos prácticos en futuras actualizaciones.",
  "Funciona bien, aunque a veces tarda un poco en cargar.",
  "Sería útil incluir una guía rápida para principiantes.",
  "La experiencia es buena, pero algunos textos tienen errores de ortografía.",
  "Consideren agregar una versión offline para mayor accesibilidad.",
  "Gran trabajo, solo faltan algunas mejoras para hacerlo perfecto.",
  "Algunos procesos podrían ser más rápidos y fluidos.",
  "Sería interesante ver integración con otras plataformas populares.",
  "El diseño es atractivo, pero la navegación no es muy clara.",
  "Las notificaciones a veces son confusas y podrían mejorarse.",
  "Sugiero añadir más opciones de idioma para llegar a más usuarios.",
  "Sería útil un tutorial inicial para nuevos usuarios.",
  "Algunas funciones no están disponibles en la versión móvil.",
  "Me gustaría que las actualizaciones fueran más frecuentes.",
  "El sistema de búsqueda podría ser más preciso y rápido.",
  "Hay algunos bugs menores que afectan la experiencia.",
  "Sería bueno tener un chat de soporte en tiempo real.",
  "Las opciones de configuración son limitadas, se podría ampliar.",
  "El contenido está bien, pero la organización podría mejorarse.",
  "Sería genial incluir más contenido interactivo.",
  "Algunas instrucciones no son claras, confunden un poco.",
  "El rendimiento general es bueno, pero puede mejorar en dispositivos antiguos.",
  "La integración con redes sociales podría ser más fluida.",
  "Se agradecería un modo oscuro para descansar la vista.",
  "Sería útil poder exportar datos o configuraciones.",
  "Algunos enlaces están rotos o llevan a páginas equivocadas.",
  "La atención al cliente es amable, pero responde lento.",
  "Sugiero mejorar la accesibilidad para personas con discapacidad.",
  "La app consume mucha batería, deberían optimizarla.",
  "El proceso de registro podría simplificarse.",
  "La personalización de perfiles es muy básica.",
  "El contenido en video podría tener subtítulos.",
  "La función de compartir debería ser más visible.",
  "Sería bueno añadir recordatorios o alertas personalizadas.",
  "La calidad del audio en algunos videos es baja.",
  "La app es muy útil, pero le falta un diseño más moderno.",
  "Sería ideal poder sincronizar con otras aplicaciones.",
  "La barra de progreso no siempre funciona correctamente.",
  "El sistema de puntuación podría ser más transparente.",
  "Se podrían añadir más opciones para compartir en redes sociales.",
  "El soporte técnico debería incluir más tutoriales y FAQ.",
  "Me gustaría que las notificaciones fueran configurables.",
  "Sería bueno tener un historial de actividades más detallado.",
  "El proceso de pago es seguro, pero falta más información clara.",
  
  // Inglés
  "I really like it, but I think some aspects could be improved.",
  "It would be great to add more customization options.",
  "The idea is excellent, just need to refine some technical details.",
  "The content is good, but the interface could be more intuitive.",
  "I’d like to see more practical examples in future updates.",
  "It works well, although it sometimes takes a bit to load.",
  "A quick-start guide for beginners would be useful.",
  "The experience is good, but some texts have typos.",
  "Consider adding an offline version for better accessibility.",
  "Great job, just some improvements needed to make it perfect.",
  "Some processes could be faster and smoother.",
  "Integration with other popular platforms would be interesting.",
  "The design is appealing but navigation isn't very clear.",
  "Notifications can be confusing and need improvement.",
  "I suggest adding more language options to reach more users.",
  "A beginner tutorial would be helpful.",
  "Some features aren't available on the mobile version.",
  "I would like updates to be more frequent.",
  "The search system could be faster and more accurate.",
  "There are some minor bugs affecting the experience.",
  "A real-time support chat would be great.",
  "Configuration options are limited and could be expanded.",
  "Content is good, but organization can be improved.",
  "Including more interactive content would be great.",
  "Some instructions aren't clear and can be confusing.",
  "Overall performance is good but can improve on older devices.",
  "Integration with social media could be smoother.",
  "A dark mode would be appreciated to ease eye strain.",
  "Ability to export data or settings would be useful.",
  "Some links are broken or lead to wrong pages.",
  "Customer support is friendly but responds slowly.",
  "Accessibility improvements for disabled users are needed.",
  "The app uses a lot of battery; optimization is necessary.",
  "The registration process could be simplified.",
  "Profile customization is very basic.",
  "Video content could have subtitles.",
  "The share function should be more visible.",
  "Adding personalized reminders or alerts would be good.",
  "Audio quality in some videos is low.",
  "The app is useful but needs a more modern design.",
  "Syncing with other apps would be ideal.",
  "Progress bars don’t always work properly.",
  "The scoring system could be more transparent.",
  "More social sharing options would be helpful.",
  "Tech support should include more tutorials and FAQs.",
  "I'd like notifications to be configurable.",
  "A more detailed activity history would be useful.",
  "The payment process is secure but lacks clear information.",
  
  // Italiano
  "Mi piace molto, ma penso che alcuni aspetti potrebbero migliorare.",
  "Sarebbe fantastico aggiungere più opzioni di personalizzazione.",
  "L’idea è eccellente, serve solo rifinire alcuni dettagli tecnici.",
  "Il contenuto è buono, ma l’interfaccia potrebbe essere più intuitiva.",
  "Mi piacerebbe vedere più esempi pratici negli aggiornamenti futuri.",
  "Funziona bene, anche se a volte impiega un po’ a caricarsi.",
  "Sarebbe utile includere una guida rapida per principianti.",
  "L’esperienza è buona, ma alcuni testi contengono errori di ortografia.",
  "Considerate di aggiungere una versione offline per una migliore accessibilità.",
  "Ottimo lavoro, servono solo alcune migliorie per renderlo perfetto.",
  "Alcuni processi potrebbero essere più veloci e fluidi.",
  "Sarebbe interessante vedere integrazione con altre piattaforme popolari.",
  "Il design è attraente ma la navigazione non è molto chiara.",
  "Le notifiche a volte sono confuse e potrebbero migliorare.",
  "Suggerisco di aggiungere più opzioni linguistiche per raggiungere più utenti.",
  "Sarebbe utile un tutorial iniziale per i nuovi utenti.",
  "Alcune funzionalità non sono disponibili nella versione mobile.",
  "Vorrei che gli aggiornamenti fossero più frequenti.",
  "Il sistema di ricerca potrebbe essere più preciso e veloce.",
  "Ci sono alcuni bug minori che influiscono sull’esperienza.",
  "Sarebbe bello avere una chat di supporto in tempo reale.",
  "Le opzioni di configurazione sono limitate e potrebbero essere ampliate.",
  "Il contenuto è buono, ma l’organizzazione potrebbe migliorare.",
  "Sarebbe fantastico includere più contenuti interattivi.",
  "Alcune istruzioni non sono chiare e confondono un po’.",
  "Le prestazioni generali sono buone, ma possono migliorare su dispositivi più vecchi.",
  "L’integrazione con i social media potrebbe essere più fluida.",
  "Sarebbe utile una modalità scura per riposare la vista.",
  "Sarebbe utile poter esportare dati o configurazioni.",
  "Alcuni link sono rotti o portano a pagine sbagliate.",
  "Il supporto clienti è gentile, ma risponde lentamente.",
  "Suggerisco di migliorare l’accessibilità per persone con disabilità.",
  "L’app consuma molta batteria, dovrebbe essere ottimizzata.",
  "Il processo di registrazione potrebbe essere semplificato.",
  "La personalizzazione del profilo è molto basica.",
  "I contenuti video potrebbero avere sottotitoli.",
  "La funzione di condivisione dovrebbe essere più visibile.",
  "Sarebbe bello aggiungere promemoria o avvisi personalizzati.",
  "La qualità audio in alcuni video è bassa.",
  "L’app è utile, ma necessita di un design più moderno.",
  "Sarebbe ideale sincronizzarsi con altre app.",
  "La barra di progresso non funziona sempre correttamente.",
  "Il sistema di punteggio potrebbe essere più trasparente.",
  "Si potrebbero aggiungere più opzioni di condivisione sui social media.",
  "Il supporto tecnico dovrebbe includere più tutorial e FAQ.",
  "Vorrei che le notifiche fossero configurabili.",
  "Sarebbe utile avere uno storico delle attività più dettagliato.",
  "Il processo di pagamento è sicuro ma manca di informazioni chiare."
];
