export const AFIRMAR = [
  // Español
  "Muy cierto eso 👏",
  "Totalmente de acuerdo ✅",
  "Así es, sin duda alguna 👍",
  "No podría estar más de acuerdo 🙌",
  "Palabras sabias 💡",
  "Justo lo que estaba pensando 🤯",
  "Exacto, bien dicho 👌",
  "100% cierto 💯",
  "No hay mejor manera de decirlo 🗣️",
  "Tienes toda la razón 🥇",
  "Lo firmo con todo ❤️",
  "Eso es verdad absoluta 📢",
  "Frase para enmarcar 🖼️",
  "Habla por mí 🙋‍♂️",
  "Así se habla, sin rodeos 🎯",
  "No se puede negar 🤷‍♀️",
  "Punto para ti 🎯",
  "Claro y conciso ✍️",
  "Perfectamente expresado 💬",
  "Me quito el sombrero 🎩",

  // Inglés
  "Very true that 👏",
  "Totally agree ✅",
  "That's right, no doubt 👍",
  "Couldn't agree more 🙌",
  "Wise words 💡",
  "Exactly what I was thinking 🤯",
  "Spot on 👌",
  "100% true 💯",
  "Couldn't have said it better 🗣️",
  "You're absolutely right 🥇",
  "I totally sign off on that ❤️",
  "That is absolute truth 📢",
  "Quote-worthy 🖼️",
  "Speaking for me 🙋‍♂️",
  "That's how you talk, no sugarcoating 🎯",
  "Can't deny that 🤷‍♀️",
  "Point for you 🎯",
  "Clear and concise ✍️",
  "Perfectly expressed 💬",
  "Hats off to you 🎩",

  // Italiano
  "Molto vero 👏",
  "Totale accordo ✅",
  "Esatto, senza dubbio 👍",
  "Non potrei essere più d'accordo 🙌",
  "Parole sagge 💡",
  "Esattamente quello che pensavo 🤯",
  "Colpito nel segno 👌",
  "100% vero 💯",
  "Non potevo dirlo meglio 🗣️",
  "Hai assolutamente ragione 🥇",
  "Firmo con tutto il cuore ❤️",
  "Questa è la verità assoluta 📢",
  "Da incorniciare 🖼️",
  "Parla per me 🙋‍♂️",
  "Così si parla, senza mezze misure 🎯",
  "Non si può negare 🤷‍♀️",
  "Punto per te 🎯",
  "Chiaro e conciso ✍️",
  "Perfettamente espresso 💬",
  "Mi tolgo il cappello 🎩"
];
