export const GOOD_CONTENT = [
  // Español
  "Esto sí que es contenido 🙌",
  "Contenido de calidad 🔥",
  "Aquí hay buen material 💯",
  "Esto merece un like 👍",
  "Contenido top, sin duda 🚀",
  "No puedo dejar de ver este contenido 😍",
  "Esto es oro puro ✨",
  "Material que vale la pena compartir 📤",
  "Un contenido que realmente aporta valor 📚",
  "Pura magia en cada palabra 🪄",
  "Simplemente impresionante 🤩",
  "Esto eleva el nivel de todo el feed ⬆️",
  "Así se hace contenido 👏",
  "¡Gracias por este contenido tan bueno! 🙏",
  "La definición de buen contenido 📈",
  "Brutalmente bueno 🔥🔥🔥",
  "Esto es lo que quiero ver más seguido 👀",
  "Un regalo para los sentidos 🎁",
  "Perfecto en todos los sentidos ✅",
  "Contenido que engancha desde el primer segundo ⏳",
  "Aquí sí que saben cómo hacer las cosas bien 🏆",
  "El contenido que necesito para el día de hoy ☀️",
  "Esto se merece un premio 🏅",
  "Calidad en estado puro 💎",
  "Un clásico instantáneo 🎬",

  // Inglés
  "Now this is content 🙌",
  "Quality content right here 🔥",
  "This is some good stuff 💯",
  "Content worth your time 👍",
  "Top-notch content 🚀",
  "Can't stop watching this content 😍",
  "Pure gold ✨",
  "Material that's worth sharing 📤",
  "Content that truly adds value 📚",
  "Magic in every word 🪄",
  "Simply stunning 🤩",
  "This raises the whole feed's level ⬆️",
  "This is how you do content 👏",
  "Thanks for such great content! 🙏",
  "The definition of good content 📈",
  "Brutally good 🔥🔥🔥",
  "This is the kind of content I want to see more often 👀",
  "A gift for the senses 🎁",
  "Perfect in every way ✅",
  "Content that hooks you from the first second ⏳",
  "They really know how to do it right 🏆",
  "The content I needed today ☀️",
  "This deserves an award 🏅",
  "Pure quality 💎",
  "An instant classic 🎬",

  // Italiano
  "Questo sì che è contenuto 🙌",
  "Contenuto di qualità 🔥",
  "Questo è del buon materiale 💯",
  "Contenuto che merita 👍",
  "Contenuto top, senza dubbio 🚀",
  "Non riesco a smettere di guardare questo contenuto 😍",
  "Oro puro ✨",
  "Materiale che vale la pena condividere 📤",
  "Contenuto che aggiunge davvero valore 📚",
  "Magia in ogni parola 🪄",
  "Semplicemente impressionante 🤩",
  "Alza il livello di tutto il feed ⬆️",
  "Così si fa contenuto 👏",
  "Grazie per questo contenuto così buono! 🙏",
  "La definizione di buon contenuto 📈",
  "Brutalmente buono 🔥🔥🔥",
  "Questo è il tipo di contenuto che voglio vedere più spesso 👀",
  "Un regalo per i sensi 🎁",
  "Perfetto in ogni modo ✅",
  "Contenuto che ti cattura dal primo secondo ⏳",
  "Qui sanno davvero come fare le cose bene 🏆",
  "Il contenuto di cui avevo bisogno oggi ☀️",
  "Questo merita un premio 🏅",
  "Qualità pura 💎",
  "Un classico istantaneo 🎬"
];
